Fix “NoSuchMethodError: org.hamcrest.Matcher.describeMismatch” in HikariCPCollectorTest#connectionClosed by using mockito-core instead of mockito-all and declaring the hamcrest dependencies before the mockito and junit dependencies.
See http://stackoverflow.com/questions/7869711/getting-nosuchmethoderror-org-hamcrest-matcher-describemismatch-when-running for details.